# Generated by Django 6.0 on 2026-01-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildingFloor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mgm_bldrgst_pk",
                    models.CharField(
                        db_index=True, help_text="관리건축물대장PK", max_length=50
                    ),
                ),
                ("flr_no", models.FloatField(help_text="층번호(숫자)")),
                (
                    "flr_no_nm",
                    models.CharField(
                        blank=True, help_text="층명칭", max_length=50, null=True
                    ),
                ),
                (
                    "flr_gb_cd",
                    models.CharField(
                        blank=True,
                        help_text="층구분코드(10:지하, 20:지상)",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("lat", models.FloatField(default=0.0, help_text="면적(㎡)")),
                (
                    "main_purps_cd_nm",
                    models.CharField(
                        blank=True, help_text="주용도코드명", max_length=100, null=True
                    ),
                ),
                (
                    "strct_cd_nm",
                    models.CharField(
                        blank=True, help_text="구조코드명", max_length=100, null=True
                    ),
                ),
                (
                    "main_atch_gb_cd_nm",
                    models.CharField(
                        blank=True, help_text="주부속구분", max_length=50, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["mgm_bldrgst_pk", "flr_no"],
                        name="maps_buildi_mgm_bld_415f05_idx",
                    )
                ],
            },
        ),
    ]
