# Generated by Django 6.0 on 2026-01-03 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0002_buildingfloor"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="buildingfloor",
            name="maps_buildi_mgm_bld_415f05_idx",
        ),
        migrations.DeleteModel(
            name="BuildingFloor",
        ),
    ]
