# Generated by Django 6.0 on 2026-01-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0003_remove_buildingfloor_maps_buildi_mgm_bld_415f05_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LandInfoCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pnu", models.CharField(db_index=True, max_length=19, unique=True)),
                ("data", models.JSONField(help_text="Land and building information")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "토지정보 캐시",
                "verbose_name_plural": "토지정보 캐시",
                "db_table": "land_info_cache",
            },
        ),
        migrations.AlterModelOptions(
            name="parcelcache",
            options={
                "verbose_name": "지적경계 캐시",
                "verbose_name_plural": "지적경계 캐시",
            },
        ),
        migrations.AlterModelTable(
            name="parcelcache",
            table="parcel_cache",
        ),
    ]
