# Generated by Django 6.0 on 2026-01-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0004_landinfocache_alter_parcelcache_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WFSCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cache_key",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("data", models.JSONField(help_text="Layer GeoJSON data")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "WFS 경계 캐시",
                "verbose_name_plural": "WFS 경계 캐시",
                "db_table": "wfs_cache",
            },
        ),
    ]
