# Generated by Django 6.0 on 2026-01-18 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0006_kamcocache"),
    ]

    operations = [
        migrations.CreateModel(
            name="WarehouseCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cache_key",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("data", models.JSONField(help_text="Warehouse items JSON data")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "물류창고 캐시",
                "verbose_name_plural": "물류창고 캐시",
                "db_table": "warehouse_cache",
            },
        ),
    ]
