# Generated by Django 6.0 on 2026-01-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0007_warehousecache"),
    ]

    operations = [
        migrations.CreateModel(
            name="HospitalCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cache_key",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("data", models.JSONField(help_text="Hospital statistics JSON data")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "병상수 캐시",
                "verbose_name_plural": "병상수 캐시",
                "db_table": "hospital_cache",
            },
        ),
    ]
